spring:
  h2:
    console:
      enabled: true # H2 Console의 사용여부를 결정
      path: /pptware # H2 Console에 접속하기 위한 경로 (URL을 의미)
  datasource:
    url: jdbc:h2:~/pptware # H2 Console에서 해당 프로젝트의 DB에 접속하기 위한 경로
  jpa:
    hibernate:
      ddl-auto: create # 애플리케이션 구동 시 JPA Database 초기화 전략 / none : 사용하지 않음 / create : 기존 테이블 삭제 후 테이블 생성 / create-drop : 기존 테이블 삭제 후 테이블 생성, 종료 시점에 테이블 삭제 / update : 변경된 스키마 적용 / validate : 엔티티와 테이블 정상 매핑 확인
    show-sql: false # DB에 날리는 쿼리문 표시 여부 / 추 후 true로 변경 예정
    properties:
      hibernate:
        format_sql: true # 쿼리문 포맷 (가독성 증가)
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true